function h = ApplyProperties(h, varargin)

if( isempty(varargin) ) 
    type  = 'MatlabDefault';
else
    type  = varargin{:};
end

switch type
    case 'MatlabDefault'
        reset(h)
            
    case 'Customized-v1'
        set(h, 'DefaultTextFontsize',14, ...
            'DefaultTextFontname','Times New Roman', ...
            'DefaultTextFontWeight','bold', ...
            'DefaultAxesFontsize',14, ...
            'DefaultAxesFontname','Times New Roman', ...
            'DefaultAxesFontWeight','bold', ...
            'DefaultLineLineWidth', 2)

    case 'Customized-v2'
        set(h, 'DefaultTextFontsize',14, ...
            'DefaultTextFontname','Times New Roman', ...
            'DefaultTextFontWeight','bold', ...
            'DefaultAxesFontsize',14, ...
            'DefaultAxesFontname','Times New Roman', ...
            'DefaultAxesFontWeight','bold', ...
            'DefaultLineLineWidth', 2.5)
        
    case 'Customized-v3'
        set(h, 'DefaultTextFontsize',12, ...
            'DefaultTextFontname','Times New Roman', ...
            'DefaultTextFontWeight','bold', ...
            'DefaultAxesFontsize',12, ...
            'DefaultAxesFontname','Times New Roman', ...
            'DefaultAxesFontWeight','bold', ...
            'DefaultLineLineWidth', 2)
        
    case 'Customized-v4'
        set(h, 'DefaultTextFontsize',20, ...
            'DefaultTextFontname','Times New Roman', ...
            'DefaultTextFontWeight','bold', ...
            'DefaultAxesFontsize',20, ...
            'DefaultAxesFontname','Times New Roman', ...
            'DefaultAxesFontWeight','bold')
        
    case 'Customized-v5'
        set(h, 'DefaultTextFontsize',20, ...
            'DefaultTextFontname','Times New Roman', ...
            'DefaultTextFontWeight','bold', ...
            'DefaultAxesFontsize',20, ...
            'DefaultAxesFontname','Times New Roman', ...
            'DefaultAxesFontWeight','bold', ...
            'DefaultLineLineWidth', 4)
        
    case 'Customized-v6'
        set(h, 'DefaultTextFontsize',11, ...
            'DefaultTextFontname','Times New Roman', ...
            'DefaultTextFontWeight','bold', ...
            'DefaultAxesFontsize',11, ...
            'DefaultAxesFontname','Times New Roman', ...
            'DefaultAxesFontWeight','bold', ...
            'DefaultLineLineWidth', 4)
        
end

end